# Generated by Django 3.1.7 on 2021-03-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_student', models.CharField(default='', max_length=50)),
                ('AM1', models.CharField(blank=True, default='', max_length=2)),
                ('AL', models.CharField(blank=True, default='', max_length=2)),
                ('FG', models.CharField(blank=True, default='', max_length=2)),
                ('FPC', models.CharField(blank=True, default='', max_length=2)),
                ('CG', models.CharField(blank=True, default='', max_length=2)),
                ('AM2', models.CharField(blank=True, default='', max_length=2)),
                ('GAD', models.CharField(blank=True, default='', max_length=2)),
                ('AN', models.CharField(blank=True, default='', max_length=2)),
                ('FM', models.CharField(blank=True, default='', max_length=2)),
                ('PC', models.CharField(blank=True, default='', max_length=2)),
                ('FC', models.CharField(blank=True, default='', max_length=2)),
                ('MCM', models.CharField(blank=True, default='', max_length=2)),
                ('ED', models.CharField(blank=True, default='', max_length=2)),
                ('TP', models.CharField(blank=True, default='', max_length=2)),
                ('POO', models.CharField(blank=True, default='', max_length=2)),
                ('EM', models.CharField(blank=True, default='', max_length=2)),
                ('TDFS', models.CharField(blank=True, default='', max_length=2)),
                ('RM', models.CharField(blank=True, default='', max_length=2)),
                ('MS', models.CharField(blank=True, default='', max_length=2)),
                ('EFM', models.CharField(blank=True, default='', max_length=2)),
                ('IO', models.CharField(blank=True, default='', max_length=2)),
                ('MC', models.CharField(blank=True, default='', max_length=2)),
                ('ET', models.CharField(blank=True, default='', max_length=2)),
                ('ANA', models.CharField(blank=True, default='', max_length=2)),
                ('ASD', models.CharField(blank=True, default='', max_length=2)),
                ('BD', models.CharField(blank=True, default='', max_length=2)),
                ('AR', models.CharField(blank=True, default='', max_length=2)),
                ('TSCO1', models.CharField(blank=True, default='', max_length=2)),
                ('MDC', models.CharField(blank=True, default='', max_length=2)),
                ('TLH', models.CharField(blank=True, default='', max_length=2)),
                ('SDGD', models.CharField(blank=True, default='', max_length=2)),
                ('TSCO2', models.CharField(blank=True, default='', max_length=2)),
                ('AF', models.CharField(blank=True, default='', max_length=2)),
                ('AS', models.CharField(blank=True, default='', max_length=2)),
                ('TA', models.CharField(blank=True, default='', max_length=2)),
                ('CO', models.CharField(blank=True, default='', max_length=2)),
                ('PCO', models.CharField(blank=True, default='', max_length=2)),
                ('FB', models.CharField(blank=True, default='', max_length=2)),
                ('AC', models.CharField(blank=True, default='', max_length=2)),
                ('SO', models.CharField(blank=True, default='', max_length=2)),
                ('Fr', models.CharField(blank=True, default='', max_length=2)),
                ('RC', models.CharField(blank=True, default='', max_length=2)),
                ('TAPI', models.CharField(blank=True, default='', max_length=2)),
                ('GID', models.CharField(blank=True, default='', max_length=2)),
                ('PAW', models.CharField(blank=True, default='', max_length=2)),
                ('Cript', models.CharField(blank=True, default='', max_length=2)),
                ('TAEFSS', models.CharField(blank=True, default='', max_length=2)),
                ('EISS', models.CharField(blank=True, default='', max_length=2)),
                ('TITC', models.CharField(blank=True, default='', max_length=2)),
                ('CVAI', models.CharField(blank=True, default='', max_length=2)),
                ('PIM', models.CharField(blank=True, default='', max_length=2)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
